WALK_TIME_LIMIT_MINUTES = 9
WALK_TIME_FALLBACK_MINUTES = 12
MAX_GRAPH_NODES = 30
OPTIMIZATION_TIMEOUT_SEC = 10

# Parking optimization (Rules.md SC-004, §6.2)
PARKING_TRANSITION_PENALTY = 25 * 60 * 10  # inter-cluster edge penalty (car-cost scale)
PARKING_COUNT_MODE_PENALTY = 100 * 60 * 100  # 주차 횟수 최소화 — 차량 이동(주차) 횟수 우선
PARKING_SCORE_DIST_WEIGHT = 0.6
PARKING_SCORE_FEE_WEIGHT = 0.4
PARKING_CANDIDATES_PER_CLUSTER = 8
PARKING_NEARBY_RADIUS_M = 1000  # POI ↔ 주차장 직선 거리 상한 (클러스터 매칭)
PARKING_WALK_MAX_DISTANCE_M = 1000  # 주차 횟수 모드: TMAP 도보 경로 거리 상한

# Kakao Local API — 주차장(PK6) 반경 검색
KAKAO_PARKING_CATEGORY_CODE = "PK6"
KAKAO_PARKING_PAGE_SIZE = 15  # 카카오 API 페이지당 최대 15건
KAKAO_PARKING_MAX_RESULTS = 45  # 카카오 category 검색 최대 45건 (단일 호출 상한)
KAKAO_PARKING_PER_POI_LIMIT = 20  # POI마다 조회할 주차장 수
KAKAO_PARKING_PER_POI_RADIUS_M = 1000  # POI 중심 반경 (카카오 PK6)
KAKAO_HUB_CANDIDATES_PER_GROUP = 5  # POI 그룹 내 겹치는 hub 후보 상위 N개
# (legacy) 여행 중심 검색 — POI별 검색으로 대체됨
KAKAO_PARKING_SEARCH_RADIUS_M = 2000
KAKAO_PARKING_MAX_DISTANCE_M = 2000
KAKAO_PUBLIC_NAME_BONUS = 0.15  # score_parking: 이름에 «공영» 포함 시 가산
PARKING_TMAP_CANDIDATE_LIMIT = 20  # 카카오 후보 중 직선거리 1차 선별 상한
PARKING_TMAP_VALIDATE_LIMIT = 10  # TMAP 도보 정밀 검사 상위 N개
PARKING_TMAP_CANDIDATE_MIN = 8
PARKING_TMAP_CANDIDATE_PER_PLACE = 2  # 동적 상한: min(20, 4 + 장소수×2)
PARKING_HAVERSINE_PREFILTER_M = 1200  # TMAP 호출 전 직선거리 1차 필터
PARKING_SEARCH_PENALTY_SEC = 7 * 60  # 목적지 주차 시 탐색·진입 부담 (도보 최소화 비교용)

# 로딩 ETA (초) — TMAP API 지연 반영
TMAP_SEC_PER_MATRIX_PAIR = 5
TMAP_SEC_PER_PARKING_LEG = 2
OPTIMIZATION_BASE_SEC = 20
TMAP_REQUEST_DELAY_SEC = 0.2  # 연속 호출 간격 — 429(rate limit) 완화
TMAP_ROUTE_MAX_RETRIES = 3
TMAP_ROUTE_RETRY_BASE_SEC = 1.0
TMAP_MIN_ROUTE_DISTANCE_M = 5  # 동일·초근접 지점은 Route API 생략
# 대한민국 대략 경계 (ER-009: 좌표 역전·해외 좌표 차단)
KOREA_LAT_MIN = 33.0
KOREA_LAT_MAX = 39.6
KOREA_LNG_MIN = 124.5
KOREA_LNG_MAX = 132.1
FORBIDDEN_EDGE_COST = 999_999_999  # 클러스터 내 POI 직행 차량 금지

OPENAI_MODEL_DEFAULT = "gpt-4o-mini"

APP_TITLE = "ParkRoute AI"
APP_TAGLINE = "주차 · 도보 · 차량을 고려한 여행 동선 최적화"
